// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DeleteConfirmController from "./delete_confirm_controller.js"
application.register("delete-confirm", DeleteConfirmController)

import RemoveAlertController from "./remove_alert_controller.js"
application.register("remove-alert", RemoveAlertController)
