# development setup

# Note: most credentials are in Rails credentials store, protected by master.key

services:

  db:
    image: mysql:8
    restart: always
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    environment:
      - RAILS_DB_HOST=db
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:
