# development setup with external (localhost) mysql

# Note: most credentials are in Rails credentials store, protected by master.key
version: "3.8"

services:

  web:
    build: .
    environment:
      - RAILS_DB_HOST=host.docker.internal
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "3000:3000"
