# development setup

version: "3.8"

services:

  db:
    image: mariadb
    restart: always
    volumes: 
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root

  web:
    build: .
    environment:
      - RAILS_DB_HOST=db
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mariadb_data:
