# development setup with external (localhost) mysql
#
# (no real reason to run this way instead of just local Rails, except
# to test connectivity to out-of-container mysql instance)
#
# Note: most credentials are in Rails credentials store, protected by master.key

services:

  web:
    build: .
    environment:
      - RAILS_DB_HOST=host.docker.internal
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "3000:3000"
