# development setup

services:

  db:
    image: mysql:8
    restart: always
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    env_file: .env.development
    volumes:
      - .:/rails:cached
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:
